// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/kevinssheva/go-backend-template/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewHealthService creates a new instance of HealthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthService {
	mock := &HealthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HealthService is an autogenerated mock type for the HealthService type
type HealthService struct {
	mock.Mock
}

type HealthService_Expecter struct {
	mock *mock.Mock
}

func (_m *HealthService) EXPECT() *HealthService_Expecter {
	return &HealthService_Expecter{mock: &_m.Mock}
}

// Ping provides a mock function for the type HealthService
func (_mock *HealthService) Ping(ctx context.Context, includeDB bool) (*domain.HealthStatus, error) {
	ret := _mock.Called(ctx, includeDB)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 *domain.HealthStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) (*domain.HealthStatus, error)); ok {
		return returnFunc(ctx, includeDB)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) *domain.HealthStatus); ok {
		r0 = returnFunc(ctx, includeDB)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.HealthStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bool) error); ok {
		r1 = returnFunc(ctx, includeDB)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HealthService_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type HealthService_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
//   - includeDB bool
func (_e *HealthService_Expecter) Ping(ctx interface{}, includeDB interface{}) *HealthService_Ping_Call {
	return &HealthService_Ping_Call{Call: _e.mock.On("Ping", ctx, includeDB)}
}

func (_c *HealthService_Ping_Call) Run(run func(ctx context.Context, includeDB bool)) *HealthService_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HealthService_Ping_Call) Return(healthStatus *domain.HealthStatus, err error) *HealthService_Ping_Call {
	_c.Call.Return(healthStatus, err)
	return _c
}

func (_c *HealthService_Ping_Call) RunAndReturn(run func(ctx context.Context, includeDB bool) (*domain.HealthStatus, error)) *HealthService_Ping_Call {
	_c.Call.Return(run)
	return _c
}
